In [17]:
import pandas as pd

In [18]:
cleansed = '/Users/beantown/PycharmProjects/master-thesis/data/processed/03_post_cleansing/'
app_data  = '/Users/beantown/PycharmProjects/master-thesis/data/processed/07_dataset_4/app/'
path = '/Users/beantown/PycharmProjects/master-thesis/data/processed/07_dataset_4/info.csv'

In [19]:
df = pd.read_csv(path)

In [20]:
df = df[(df.val==True) | (df.val ==True)]

In [21]:
df

,Unnamed: 0,image,label,original_image,train,test,val,fragment,patchpixelcm,patch
15040,38715,0_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,0
15041,38716,1_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,1
15042,38717,2_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,2
15043,38718,3_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,3
15044,38719,4_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,4
...,...,...,...,...,...,...,...,...,...,...
21905,48485,0_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,0
21906,48486,1_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,1
21907,48487,2_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,2
21908,48488,3_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,3
21909,48489,4_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,4

In [22]:
df.drop_duplicates(subset=['original_image']).to_csv('info.csv')

In [23]:
df

,Unnamed: 0,image,label,original_image,train,test,val,fragment,patchpixelcm,patch
15040,38715,0_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,0
15041,38716,1_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,1
15042,38717,2_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,2
15043,38718,3_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,3
15044,38719,4_0_12178_4275Z6R.jpg,12178,0_12178_4275Z6R.png,False,True,False,0,NaN,4
...,...,...,...,...,...,...,...,...,...,...
21905,48485,0_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,0
21906,48486,1_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,1
21907,48487,2_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,2
21908,48488,3_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,3
21909,48489,4_7_13899_4801DV.jpg,13899,7_13899_4801DV.png,False,False,True,7,NaN,4

In [24]:
test_labels = df.label.unique()

In [25]:
test_files = df.original_image.unique()

In [26]:
test_file = test_files[0]

In [27]:
test_file

'0_12178_4275Z6R.png'

In [28]:
!cp $cleansed$test_file $app_data$test_file

In [29]:
for test_file in test_files:
    !cp $cleansed$test_file $app_data

In [16]:
len(test_files)

700

In [38]:
df['label'].mode()[0]

11438